feat: composite credential *WIP*
UnumID/schema-sdk pull request #65
Opened 2023-07-21 01:48 UTC by leo1994

[Ticket]()

## Summary

## Changes

## Testing

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas _to a borderline excessive amount_
- [ ] I have made any relevant corresponding changes to the documentation including the project readme.
- [ ] I have run and tested the changes locally
- [ ] If it is a core feature, I have added an appropriate amount of unit tests.
- [ ] Any dependent changes have been merged and published in upstream projects

2023-07-26 06:57 UTC, rsmets reviewed
Mind updating the readme section with how to add a json schema now? 

Sorry I know I said not necessary for this pr, but given I have still not properly reviewed it might as well be somewhat complete. 

I promise todo a real review first thing tomorrow!

2023-07-26 15:40 UTC, rsmets requested changes

2023-07-26 15:40 UTC, rsmets commented on package.json
> -    "jest": "jest --forceExit --runInBand",
Curious what this watch flag does, did you mean to commit this (I hate how there is no way to leave inline comments in json... I would love if this was package.yaml instead

2023-07-26 15:40 UTC, rsmets commented on src/ajv.ts
> +import Ajv2019 from 'ajv/dist/2019';
Is Ajv2019 newer than Ajv 6? _Odd that a 2019 version is newest!_

2023-07-26 15:40 UTC, rsmets commented on src/ajv.ts
> +  coerceTypes: true, // ref: https://ajv.js.org/guide/modifying-data.html#coercing-data-types,
Thank for including the `ref` comment. However, mind also adding a brief explanation of why this is important before the `ref`? (yes, I know the link can be clicked but still requires some reading a understanding... hopefully a few words drives home why we need this.

2023-07-26 15:40 UTC, rsmets commented on src/jsonSchemas/atomicCredential/currencyCredential.ts
> +      description: 'The currency of the amount.',
```suggestion
      description: 'The iso4217 currency code'
```

2023-07-26 15:40 UTC, rsmets commented on src/jsonSchemas/atomicCredential/currencyCredential.ts
> +      description: 'The currency of the amount.',
No correlation to amount in this credential schema, I feel should not be in the description.

2023-07-26 15:40 UTC, rsmets commented on src/jsonSchemas/backwardsCredential/index.ts
> +export const governmentIdDocumentImageCredentialJsonSchema = Type.Object(
Mind adding a block header of why we need these "backward compatible" schemas? Are they deprecated?

2023-07-26 15:40 UTC, rsmets commented on src/jsonSchemas/compositeCredential/annualIncomeCredential.ts
> +    // Allow backward compatibility with the old format
I forgot what our plan is to phase out these old string only values. Do we have one?

2023-07-26 15:40 UTC, rsmets commented on src/jsonSchemas/index.ts
> +  // Address Credential
Thanks for grouping these

2023-07-26 15:40 UTC, rsmets commented on src/jsonSchemas/individualCredential/facialImageCredential.ts
> +export const facialImageCredentialJsonSchema = Type.Object(
I forget how we are relating facialImage to gov doc and match creds?

2023-07-26 15:40 UTC, rsmets commented on src/formats.ts
> +export const iso3166USRegionCodeFormat: Format = {
Mind adding unit tests for these new formats? I do not see any for them.

2023-07-26 15:47 UTC, leo1994 commented on src/jsonSchemas/individualCredential/facialImageCredential.ts
> +export const facialImageCredentialJsonSchema = Type.Object(
We're not doing it yet, because this thing of being linked or not, I'll leave it for when I close this task, because it involves another complexity

2023-07-26 15:49 UTC, leo1994 commented on src/formats.ts
> +export const iso3166USRegionCodeFormat: Format = {
I'll do this

2023-07-26 15:50 UTC, leo1994 commented on src/formats.ts
> -  'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA',
I dont know, I'll try figure out

2023-07-26 15:51 UTC, leo1994 commented on src/type/index.ts
> +export class TypeBuilder extends ExtendedTypeBuilder {
I instantiate it down there and export

2023-07-26 15:54 UTC, leo1994 commented on src/jsonSchemas/individualCredential/firstNameCredential.ts
> +export const firstNameCredentialJsonSchema = Type.Object(
Individual who I think is related to someone, so the credential itself provides some relevant information. Example first name is self-validating information, match credential says nothing

2023-07-26 15:56 UTC, leo1994 commented on src/jsonSchemas/compositeCredential/fullNameCredential.ts
> +    Type.Object(
I'm not exactly sure how we can handle this problem, I think we can end this thinking about backwards compatibility and create a task to deprecate what we want

2023-07-26 15:57 UTC, leo1994 commented on src/jsonSchemas/compositeCredential/annualIncomeCredential.ts
> +    // Allow backward compatibility with the old format
Same ? https://github.com/UnumID/schema-sdk/pull/65#discussion_r1275182913

2023-07-26 16:00 UTC, leo1994 commented on src/jsonSchemas/backwardsCredential/index.ts
> +export const governmentIdDocumentImageCredentialJsonSchema = Type.Object(
if no one is using it, we can remove

I think these two are being used by unest, right?
```typescript
...
  IncomeCurrencyCredential: incomeCurrencyCredentialJsonSchema,
  AnnualIncomeRangeCredential: annualIncomeRangeCredentialJsonSchema
}
```

2023-07-26 16:04 UTC, leo1994 commented on src/ajv.ts
> +import Ajv2019 from 'ajv/dist/2019';
No, this is just used to support all new JSON Schema draft-2019-09 keywords

2023-07-26 21:00 UTC, leo1994 commented on src/formats.ts
> +export const iso3166USRegionCodeFormat: Format = {
https://github.com/UnumID/schema-sdk/pull/65/files#diff-457dabd2082c54d531487d5b4f7cdf7a25c97ab052b274b500c957004606039fR217-R322

2023-07-26 21:46 UTC, rsmets commented on src/ajv.ts
> +import Ajv2019 from 'ajv/dist/2019';
Strange that the 2019 keywords have not made it into more recent AJV versions =/

2023-07-26 21:47 UTC, rsmets commented on src/ajv.ts
> +  coerceTypes: true, // ref: https://ajv.js.org/guide/modifying-data.html#coercing-data-types,
Hmm I guess that was me. I wish I included why this setting was necessary.

2023-07-26 21:48 UTC, rsmets commented on src/type/index.ts
> +export class TypeBuilder extends ExtendedTypeBuilder {
Right but then where is it imported?

2023-07-26 21:48 UTC, rsmets commented on src/formats.ts
> -  'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA',
Thanks, if a pain no big deal.

2023-07-26 21:49 UTC, rsmets commented on src/formats.ts
> +export const iso3166USRegionCodeFormat: Format = {
Oops I must have somehow missed the format test file update. Thanks.

2023-07-26 21:49 UTC, rsmets commented on src/jsonSchemas/addressCredential/stateCredential.ts
> +        country: { const: 'US' }
@leo1994 mind answering this?

2023-07-26 21:49 UTC, rsmets commented on src/jsonSchemas/addressCredential/zipCodeCredential.ts
> +        country: { const: 'US' }
@leo1994 mind answering this?

2023-07-26 21:50 UTC, rsmets commented
Also, oops sorry my description suggestion had a typo in it

2023-07-26 21:52 UTC, rsmets reviewed
Looks good mostly good. But still a couple questions regarding where the json schema conditional validation works. (tagged in them a moment ago). and the readme still needs to be updated with how to add new json schemas.

2023-07-26 22:30 UTC, leo1994 commented on src/jsonSchemas/addressCredential/stateCredential.ts
> +        country: { const: 'US' }
Oh, I added a description for this

https://github.com/UnumID/schema-sdk/pull/65/files#diff-e3a02a9782b6031b8f6c9be0e8b0ebd427e3f98aa4f0126ec9c37c7e0c21b5b1R14-R25

2023-07-26 22:48 UTC, leo1994 commented on src/type/index.ts
> +export class TypeBuilder extends ExtendedTypeBuilder {
Oh, in credentials files `import { Type } from '../../type';`

2023-07-26 22:50 UTC, leo1994 commented
> Looks good mostly good. But still a couple questions regarding where the json schema conditional validation works. (tagged in them a moment ago). and the readme still needs to be updated with how to add new json schemas.

Oh I updated the readme.md, I just forget to mention and also add description to If statement

2023-07-26 22:51 UTC, leo1994 commented on src/jsonSchemas/addressCredential/zipCodeCredential.ts
> +        country: { const: 'US' }
Oh, I added a description for this

[#65 (files)](https://github.com/UnumID/schema-sdk/pull/65/files#diff-e3a02a9782b6031b8f6c9be0e8b0ebd427e3f98aa4f0126ec9c37c7e0c21b5b1R14-R25)

2023-07-26 22:58 UTC, leo1994 commented on src/ajv.ts
> +  coerceTypes: true, // ref: https://ajv.js.org/guide/modifying-data.html#coercing-data-types,
I also don't know why it's necessary.
I know how it works because I had several problems with this property enabled in the Core-service, when I was working on the task of removing credentials that were expired, this property converted `null` to `0`

2023-07-26 23:07 UTC, leo1994 commented on src/ajv.ts
> +import Ajv2019 from 'ajv/dist/2019';
AJV can use all JSON Schemas draft, they just use [Json Schema Draft 7 ](https://ajv.js.org/json-schema.html#draft-07) as default because has better performance.

But because we need the new features of later versions, we need specify the draft version

2023-07-27 15:58 UTC, rsmets approved these changes
Conditional approval. Just please add some links to the readme updates.

2023-07-27 15:58 UTC, rsmets commented on src/jsonSchemas/backwardsCredential/index.ts
> +export const governmentIdDocumentImageCredentialJsonSchema = Type.Object(
I think only `AnnualIncomeRangeCredential` but I would have to check.

2023-07-27 15:58 UTC, rsmets commented on src/jsonSchemas/compositeCredential/fullNameCredential.ts
> +    Type.Object(
Okay. We will deal with this at a later point and continue to tell people fullname string is deprecated.

2023-07-27 19:05 UTC, leo1994 commented
Updated README

2023-07-27 19:18 UTC, merged